export const getAllCategoriesTypes = {
  SET_GET_ALL_CATEGORIES: "CATEGORY/SET_GET_ALL_CATEGORIES",
  SET_GET_ALL_CATEGORIES_LOADING: "CATEGORY/SET_GET_ALL_CATEGORIES_LOADING",
  SET_GET_ALL_CATEGORIES_ERROR: "CATEGORY/SET_GET_ALL_CATEGORIES_ERROR"
};
