export const getPaniersByCommandTypes = {
  SET_GET_PANIERS_BY_COMMAND: "COMMAND/SET_GET_PANIERS_BY_COMMAND",
  SET_GET_PANIERS_BY_COMMAND_LOADING:
    "COMMAND/SET_GET_PANIERS_BY_COMMAND_LOADING",
  SET_GET_PANIERS_BY_COMMAND_ERROR: "COMMAND/SET_GET_PANIERS_BY_COMMAND_ERROR"
};
