export const getAllProductsTypes = {
  SET_GET_ALL_PRODUCTS: "PRODUCT/SET_GET_ALL_PRODUCTS",
  SET_GET_ALL_PRODUCTS_LOADING: "PRODUCT/SET_GET_ALL_PRODUCTS_LOADING",
  SET_GET_ALL_PRODUCTS_ERROR: "PRODUCT/SET_GET_ALL_PRODUCTS_ERROR"
};

export const getInfoProductTypes = {
  SET_GET_INFO_PRODUCT: "PRODUCT/SET_GET_INFO_PRODUCT",
  SET_GET_INFO_PRODUCT_LOADING: "PRODUCT/SET_GET_INFO_PRODUCT_LOADING",
  SET_GET_INFO_PRODUCT_ERROR: "PRODUCT/SET_GET_INFO_PRODUCT_ERROR"
};
