export const getAllProductsTypes = {
  SET_GET_ALL_PRODUCTS: "PRODUCT/SET_GET_ALL_USERS",
  SET_GET_ALL_PRODUCTS_LOADING: "PRODUCT/SET_GET_ALL_PRODUCTS_LOADING",
  SET_GET_ALL_PRODUCTS_ERROR: "PRODUCT/SET_GET_ALL_PRODUCTS_ERROR"
};
