export const getAllClientsTypes = {
  SET_GET_ALL_CLIENTS: "USER/SET_GET_ALL_CLIENTS",
  SET_GET_ALL_CLIENTS_LOADING: "USER/SET_GET_ALL_CLIENTS_LOADING",
  SET_GET_ALL_CLIENTS_ERROR: "USER/SET_GET_ALL_CLIENTS_ERROR"
};
